import { NextRequest, NextResponse } from 'next/server'
import { getAuthUser } from '@/lib/auth-helper'
import { db } from '@/lib/db'

// Helper to push a file to GitHub
async function pushFileToGitHub(token: string, owner: string, repo: string, path: string, content: string, message: string) {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`
    const body: any = {
        message,
        content: Buffer.from(content).toString('base64'),
    }

    // Check if file exists to get SHA for update
    try {
        const checkRes = await fetch(url, {
            headers: { Authorization: `Bearer ${token}` }
        })
        if (checkRes.ok) {
            const data = await checkRes.json()
            body.sha = data.sha
        }
    } catch (e) { /* ignore */ }

    const res = await fetch(url, {
        method: 'PUT',
        headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
            'User-Agent': 'Ace-Builder'
        },
        body: JSON.stringify(body)
    })

    if (!res.ok) {
        const err = await res.json()
        throw new Error(`GitHub File Error (${path}): ${err.message}`)
    }
}

export async function POST(request: NextRequest) {
    try {
        const user = await getAuthUser(request)
        if (!user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const { vercelToken, subdomain, siteContent } = await request.json()

        if (!vercelToken || !subdomain) {
            return NextResponse.json({ error: 'Missing Vercel token or subdomain' }, { status: 400 })
        }

        // 1. Get GitHub Token from Linked Account
        const account = await db.account.findFirst({
            where: {
                userId: user.id,
                provider: 'github'
            }
        })

        if (!account || !account.access_token) {
            return NextResponse.json({ error: 'GitHub account not connected. Please connect GitHub first.' }, { status: 400 })
        }

        const githubToken = account.access_token

        // 2. Get GitHub User Info
        const ghUserRes = await fetch('https://api.github.com/user', {
            headers: { Authorization: `Bearer ${githubToken}` }
        })
        if (!ghUserRes.ok) throw new Error('Invalid GitHub Token or Session Expired')
        const ghUser = await ghUserRes.json()
        const ghUsername = ghUser.login

        // 3. Create/Get GitHub Repo
        const repoName = `ace-site-${subdomain}`
        let repoUrl = ''

        const createRepoRes = await fetch('https://api.github.com/user/repos', {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${githubToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                name: repoName,
                private: true,
                auto_init: true,
                description: `Generated by Ace AutoFood for ${subdomain}`
            })
        })

        if (createRepoRes.status === 422) {
            // Repo likely exists, proceed using it
            repoUrl = `https://github.com/${ghUsername}/${repoName}`
        } else if (!createRepoRes.ok) {
            const err = await createRepoRes.json()
            throw new Error(`Failed to create GitHub repo: ${err.message}`)
        } else {
            repoUrl = (await createRepoRes.json()).html_url
        }

        // 4. Push Code to GitHub

        const packageJson = {
            "name": repoName,
            "version": "0.1.0",
            "private": true,
            "scripts": { "dev": "next dev", "build": "next build", "start": "next start" },
            "dependencies": {
                "next": "14.1.0",
                "react": "^18",
                "react-dom": "^18",
                "lucide-react": "^0.300.0",
                "clsx": "^2.0.0",
                "tailwind-merge": "^2.0.0"
            },
            "devDependencies": {
                "autoprefixer": "^10.0.1",
                "postcss": "^8",
                "tailwindcss": "^3.3.0",
                "typescript": "^5"
            }
        }

        // Push package.json
        await pushFileToGitHub(githubToken, ghUsername, repoName, 'package.json', JSON.stringify(packageJson, null, 2), 'Init package.json')

        // Push next.config.js
        const nextConfig = `
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}
module.exports = nextConfig
`
        await pushFileToGitHub(githubToken, ghUsername, repoName, 'next.config.js', nextConfig, 'Init next.config.js')

        // Push Main Page (Simulated logic to inject content)
        // We inject the JSON content into a simple renderer template
        const pageContent = `
'use client'
import React, { useState } from 'react'
import { Plus, Minus, ShoppingCart, User, Phone, Globe } from 'lucide-react'

// INJECTED CONTENT
const generatedContent = ${JSON.stringify(siteContent, null, 2)}
const subdomain = "${subdomain}"

export default function Home() {
  const [lang, setLang] = useState('uz')
  const t = (obj: any) => obj ? obj[lang] : ''
  
  return (
    <div className="min-h-screen bg-slate-50 font-sans">
       <nav className="bg-white border-b py-4 px-6 flex justify-between items-center sticky top-0 z-50">
          <h1 className="text-xl font-bold uppercase">{subdomain}</h1>
          <div className="flex gap-2">
             <button onClick={() => setLang('uz')} className={lang==='uz'?'font-bold':''}>UZ</button>
             <button onClick={() => setLang('ru')} className={lang==='ru'?'font-bold':''}>RU</button>
             <button onClick={() => setLang('en')} className={lang==='en'?'font-bold':''}>EN</button>
          </div>
       </nav>
       
       <header className="py-20 text-center bg-gradient-to-b from-purple-50 to-white px-4">
          <h1 className="text-4xl font-extrabold mb-4">{t(generatedContent.hero.title)}</h1>
          <p className="text-xl text-slate-500 mb-8">{t(generatedContent.hero.subtitle)}</p>
          <a href="tel:998977087373" className="bg-primary text-white px-8 py-3 rounded-full font-bold shadow-lg hover:shadow-xl transition inline-flex items-center gap-2" style={{backgroundColor: '#7c3aed'}}>
             <Phone size={20} />
             {t(generatedContent.hero.cta)}
          </a>
       </header>

       <section className="py-16 container mx-auto px-4 grid md:grid-cols-3 gap-6">
          {generatedContent.pricing.map((plan: any, i: number) => (
             <div key={i} className="bg-white p-6 rounded-2xl shadow-sm border hover:shadow-md transition">
                <h3 className="text-2xl font-bold mb-2">{t(plan.name)}</h3>
                <div className="text-4xl font-extrabold text-purple-600 mb-4">{plan.price}</div>
                <ul className="space-y-2 mb-6 text-slate-600">
                    {plan.features.map((f: any, j: number) => (
                        <li key={j}>âœ“ {t(f)}</li>
                    ))}
                </ul>
                <a href="tel:998977087373" className="block w-full text-center py-3 rounded-xl bg-slate-100 hover:bg-slate-200 font-medium transition">
                   Select Plan
                </a>
             </div>
          ))}
       </section>
       
       <footer className="py-8 text-center text-slate-400 text-sm">
         &copy; 2024 {subdomain}
       </footer>
    </div>
  )
}
`
        // Push the page.tsx (src/app/page.tsx or pages/index.js depending on structure, using App Router structure here)
        await pushFileToGitHub(githubToken, ghUsername, repoName, 'src/app/page.tsx', pageContent, 'Deploy site content')

        // Push layout.tsx & globals.css (Minimal)
        const layoutContent = `
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${subdomain} - AutoFood Site',
  description: 'Generated by AutoFood',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
        await pushFileToGitHub(githubToken, ghUsername, repoName, 'src/app/layout.tsx', layoutContent, 'Init layout.tsx')

        const globalsCss = `
@tailwind base;
@tailwind components;
@tailwind utilities;
`
        await pushFileToGitHub(githubToken, ghUsername, repoName, 'src/app/globals.css', globalsCss, 'Init globals.css')


        // 5. Create Vercel Project
        const vercelRes = await fetch('https://api.vercel.com/v9/projects', {
            method: 'POST',
            headers: { Authorization: `Bearer ${vercelToken}` },
            body: JSON.stringify({
                name: repoName,
                framework: 'nextjs',
                gitRepository: {
                    type: 'github',
                    repo: `${ghUsername}/${repoName}`
                }
            })
        })

        let deploymentUrl = ''
        if (vercelRes.ok) {
            const vData = await vercelRes.json()
            deploymentUrl = `https://${vData.alias?.[0] || vData.name + '.vercel.app'}`
        } else {
            // If project exists, try to get it, or just ignore and return repo url
            console.warn('Vercel project creation failed (might exist):', await vercelRes.text())
            deploymentUrl = `https://${repoName}.vercel.app` // best guess
        }

        // 6. Update DB
        // Check if website entry exists, create if not
        const website = await db.website.upsert({
            where: { adminId: user.id },
            update: {
                vercelToken,
                repoName,
                content: JSON.stringify(siteContent) // Save latest content
            },
            create: {
                adminId: user.id,
                subdomain,
                theme: '{}',
                content: JSON.stringify(siteContent),
                vercelToken,
                repoName
            }
        })

        return NextResponse.json({
            success: true,
            repoUrl,
            deploymentUrl
        })

    } catch (error) {
        console.error('Deploy error:', error)
        return NextResponse.json({
            error: error instanceof Error ? error.message : 'Deployment failed'
        }, { status: 500 })
    }
}
